name: PR Workflow Example

on:
  pull_request:
    branches:
      - main  # Triggers when a PR targets the 'main' branch.

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Echo Messages
        run: |
          echo "Running CI for Pull Request"
          echo "Pull Request Number: ${{ github.event.number }}"
          echo "Branch Name: ${{ github.head_ref }}"

      - name: Run Tests (Example)
        run: |
          echo "Running tests..."
          # Add your test commands here, e.g., npm test, pytest, etc.
          echo "Tests passed successfully!"

      - name: Approve and Merge PR (Optional)
        if: success()  # Merge only if all previous steps succeed.
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
