name: Echo Message Example

on:
  push:
    branches:
      - main  # Triggers the workflow when code is pushed to the 'main' branch.

jobs:
  echo-message:
    runs-on: ubuntu-latest  # Specifies the environment to run the job.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out your repository code.

      - name: Print Echo Messages
        run: |
          echo "Hello, World!"
          echo "Current Date and Time: $(date)"
          echo "This workflow is running on branch ${{ github.ref }}"
